services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - postgres

  # backend:
  #   build:
  #     context: .
  #     dockerfile: apps/backend/Dockerfile
  #   container_name: backend
  #   ports:
  #     - "3003:3003"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - ./uploads:/app/uploads

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: apps/frontend/Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

  # admin:
  #   build:
  #     context: .
  #     dockerfile: apps/admin/Dockerfile
  #   container_name: admin
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
      - '8081:8081'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/usr/share/nginx/html/uploads
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - nx

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./certbot-init.sh:/scripts/certbot-init.sh
    entrypoint: '/scripts/certbot-init.sh'
    environment:
      - DOMAIN=bingeit.hopto.org
      - EMAIL=harshitvermaofficial@gmail.com

  nx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nx
    ports:
      - '3000:3000' # ott
      - '3001:3001' # admin
      - '3003:3003' # backend
      - '3004:3004' # landing
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
      NX_DAEMON: true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nx

volumes:
  postgres-data:
