services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # backend:
  #   build:
  #     context: .
  #     dockerfile: apps/backend/Dockerfile
  #   container_name: backend
  #   ports:
  #     - "3003:3003"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: apps/frontend/Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

  # admin:
  #   build:
  #     context: .
  #     dockerfile: apps/admin/Dockerfile
  #   container_name: admin
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

  nx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nx
    ports:
      - "3000:3000" # frontend
      - "3001:3001" # admin
      - "3003:3003" # backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data:
